name: Sync Fork
on:
  schedule:
    - cron: '20 0 * * *'  # Runs daily
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork
        uses: actions/checkout@v3
      - name: Setup Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "louisphilipshahim@gmail.com"
      - name: Add upstream
        run: git remote add upstream https://github.com/<original-owner>/<original-repo>.git
      - name: Fetch upstream
        run: git fetch upstream
      - name: Rebase fork
        run: git rebase upstream/main
      - name: Push changes
        run: git push origin main --force